baseurl = "https://sie-basic-eco.netlify.app/"
languageCode = "en-us"
title = "Basic Eco Web site for SIE"
theme = "Mainroad"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params.logo]
  subtitle = "Lesson at Grenoble Inp - IEM" # Logo subtitle



[[menu.main]]
    name = "Caseine"
    url = "https://caseine.org/course/view.php?id=347"
    weight = 2

    
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10


[[menu.main]]
    name = "Lessons"
    url = "/lessons_list/"
    weight = 3


[[menu.main]]
    name = "Recordings"
    url = "/Recordings/"
    weight = 4
    
    
[[menu.main]]
    name = "Other Classes"
    url = "/OtherClass/"
    weight = 6
[Params]
  description = "Basic Economics for SIE" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = false
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

