---
title: "Basic Economics for IE"
subtitle: "Lessons list"
author: "Iragaël Joly"
date: "Automn 2020"
categories: ["R"]
tags: ["lessons list"]
authorbox: false
---

# Lessons list

This is the website of the Lesson **Basic Economics for IE** taught at Grenoble INP Industrial Engineering and Management School.

## First Lesson - 01/10/2020 - Thursday 13:30-16:30

Welcome page of [First Lesson](../post/2020_10_01_first-lesson)

### To do before **Lesson 3**: Production Case Study team work 

Presentation of the team works: [Production case study](../post/2020_10_02_Production-Case-Study)

## Second Lesson - 05/10/2020 - Monday 12:00-13:30

Material for the [Second Lesson](/post/2020_10_05_second-lesson) 

## Third Lesson - 08/10/2020 - Thurday 13:30-16:30

Material for the [Third Lesson](/post/2020_10_08_third-lesson) 

## Fourth Lesson - 12/10/2020 - Monday 12:00-13:30

Material for the [Fourth Lesson](/post/2020_10_12_fourth-lesson) 

### To do before **Lesson 5**: Consumption Case Study team work 

Presentation of the team works: [Consumption case study](../post/2020_10_15_Consumption-Case-Study)

## Fifth Lesson - 15/10/2020 - Thurday 13:30-16:30

Material for the [Fifth Lesson](/post/2020_10_15_fifth-lesson) 

## Sixth Lesson - 22/10/2020 - Thurday 13:30-16:30

Material for the [Sixth Lesson](/post/2020_10_22_sixth-lesson) 

